/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controllerBarang;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.modelbarang;
import util.koneksi;

/**
 *
 * @author Anri
 */
public class viewbarang extends javax.swing.JFrame {

    koneksi koneksi = new koneksi();
    controllerBarang cp = new controllerBarang();
    modelbarang mp = new modelbarang();

    /**
     * Creates new form viewbarang
     */
    public viewbarang() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
        batalbaru();
    }

    private void baru() {
        jButtonbaru.setText("batal");
        jButtonhapus.setEnabled(false);
        jButtonbersih.setEnabled(false);
        jButtonubah.setEnabled(false);
        jButtonsimpan.setEnabled(true);
        jTextFieldnama.setEnabled(true);
        jTextFieldjenis.setEnabled(true);
        jTextFieldjumlah.setEnabled(true);
        jButton6.setEnabled(true);
    }
private void batalbaru() {
        jButtonbaru.setText("baru");
        jButtonhapus.setEnabled(false);
        jButtonbersih.setEnabled(false);
        jButtonubah.setEnabled(false);
        jButtonsimpan.setEnabled(false);
        jTextFieldnama.setEnabled(true);
        jTextFieldjenis.setEnabled(true);
        jTextFieldjumlah.setEnabled(true);
        jButton6.setEnabled(true);
    }
    private void bersih() {
        jTextFieldid.setText("");
        jTextFieldnama.setText("");
        jTextFieldjenis.setText("");
        jTextFieldjumlah.setText("");
        baru();
        
        jButtonsimpan.setEnabled(false);
        jButtonbersih.setEnabled(false);
        jTextFieldnama.setEnabled(false);
        jTextFieldjenis.setEnabled(false);
        jTextFieldjumlah.setEnabled(false);

    }

    private void ubahdanhapus() {
        jButtonhapus.setEnabled(true);
        jButtonbersih.setEnabled(true);
        jButtonubah.setEnabled(true);
        jTextFieldnama.setEnabled(true);
        jTextFieldjenis.setEnabled(true);
        jTextFieldjumlah.setEnabled(true);
    }

    private void datatable() {
        koneksi.koneksidatabase();

        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("id");
        tabel.addColumn("nama");
        tabel.addColumn("jenis");
        tabel.addColumn("jumlah");
        jTable3.setModel(tabel);
        try {
            String data = "select *from tbl_barang";
            ResultSet res = koneksi.state.executeQuery(data);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getString("jumlah")

                });
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldnama = new javax.swing.JTextField();
        jTextFieldjenis = new javax.swing.JTextField();
        jTextFieldjumlah = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButtonbaru = new javax.swing.JButton();
        jButtonubah = new javax.swing.JButton();
        jButtonsimpan = new javax.swing.JButton();
        jButtonbersih = new javax.swing.JButton();
        jButtonhapus = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Jenis Barang");

        jLabel4.setText("Jumlah barang");

        jTextFieldid.setEnabled(false);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButtonbaru.setText("Baru");
        jButtonbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbaruActionPerformed(evt);
            }
        });

        jButtonubah.setText("ubah");
        jButtonubah.setEnabled(false);
        jButtonubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonubahActionPerformed(evt);
            }
        });

        jButtonsimpan.setText("Simpan");
        jButtonsimpan.setEnabled(false);
        jButtonsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsimpanActionPerformed(evt);
            }
        });

        jButtonbersih.setText("bersih");
        jButtonbersih.setEnabled(false);
        jButtonbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbersihActionPerformed(evt);
            }
        });

        jButtonhapus.setText("hapus");
        jButtonhapus.setEnabled(false);
        jButtonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhapusActionPerformed(evt);
            }
        });

        jButton6.setText("Tutup");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldid, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jTextFieldnama))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jTextFieldjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonsimpan)
                                    .addComponent(jButtonbaru))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonubah)
                                    .addComponent(jButtonbersih)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButtonhapus)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonbaru)
                        .addComponent(jButtonubah)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsimpan)
                    .addComponent(jButtonbersih))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonhapus)
                    .addComponent(jButton6)
                    .addComponent(jTextFieldjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        ubahdanhapus();
        try {
            int baris =jTable3.getSelectedRow();
            jTextFieldid.setText(jTable3.getValueAt(baris, 0).toString());
            jTextFieldnama.setText(jTable3.getValueAt(baris, 1).toString());
            
            jTextFieldjenis.setText(jTable3.getValueAt(baris, 2).toString());
            jTextFieldjumlah.setText(jTable3.getValueAt(baris, 3).toString());
        } catch (NullPointerException e) {
            System.err.println(""+e);
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButtonbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbaruActionPerformed
        // TODO add your handling code here:
        
        String logic =jButtonbaru.getText();
        if(logic.equals("baru")){
            baru();
           
        }else{
            batalbaru();
        }
    }//GEN-LAST:event_jButtonbaruActionPerformed

    private void jButtonsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsimpanActionPerformed
        // TODO add your handling code here:
        try {
          String nama =jTextFieldnama.getText();
            String jenis =jTextFieldjenis.getText();
            int jumlah =Integer.parseInt(jTextFieldjumlah.getText());
            mp.setNamabarang(nama);
            mp.setJenisbarang(jenis);
            mp.setJumlahbarang(jumlah);
            cp.simpandata(mp);
            datatable();
            bersih();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"harap masukan data" );
        }
    }//GEN-LAST:event_jButtonsimpanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbersihActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButtonbersihActionPerformed

    private void jButtonubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonubahActionPerformed
        // TODO add your handling code here:
        try {
            int id =Integer.parseInt(jTextFieldid.getText());
            String nama =jTextFieldnama.getText();
            String jenis =jTextFieldjenis.getText();
            int jumlah =Integer.parseInt(jTextFieldjumlah.getText());
            mp.setId(id);
            mp.setNamabarang(nama);
            mp.setJenisbarang(jenis);
            mp.setJumlahbarang(jumlah);
            cp.ubahdata(mp);
            datatable();
            bersih();
            
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null,"harap mausukan angka " );
        }
    }//GEN-LAST:event_jButtonubahActionPerformed

    private void jButtonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextFieldid.getText().trim());
            mp.setId(id);
            cp.hapusdata(mp);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonhapusActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonbaru;
    private javax.swing.JButton jButtonbersih;
    private javax.swing.JButton jButtonhapus;
    private javax.swing.JButton jButtonsimpan;
    private javax.swing.JButton jButtonubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldjenis;
    private javax.swing.JTextField jTextFieldjumlah;
    private javax.swing.JTextField jTextFieldnama;
    // End of variables declaration//GEN-END:variables

}
